server:
  port: 8080
  #context_path: /liudi
  #tomcat:
    #uri-encoding: utf-8
spring:
  application:
    name: high-concurrency-e-commerce-sec-kill

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/happyshopping?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/happyshopping?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    initialSize: 100
    minIdle: 50
    maxActive: 1000
    timeBetweenEvictionRunsMillis: 2000

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 10
#    password: 1234
#    poolMaxTotal: 1000
#    poolMaxIdle: 500
#    poolMaxWait: 500

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true

    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

#  resources:
#    add-mappings: true
#    cache-period: 3600
#    chain:
#      cache: true
#      enabled: true
#      gzipped: true
#      html-application-cache: true
#    static-locations: classpath:/static/


logging:
  level:
    com.liudi: debug

mybatis:
  type-aliases-package: com.liudi.happyshopping.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapperLocations: classpath:com/liudi/happyshopping/dao/*.xml

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 10
  #password: 1234
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500